name: docker build container

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-container:
    runs-on: ubuntu-latest

    steps:
      - name: build docker image
        uses: senzing-factory/github-action-docker-buildx-build@v1
        with:
          build-options: --build-arg SENZING_ACCEPT_EULA=I_ACCEPT_THE_SENZING_EULA
          image-repository: senzing/wrap-image-with-senzing-apt
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          platforms: linux/amd64
          username: ${{ secrets.DOCKERHUB_USERNAME }}
